name: finance
description: A production-ready Flutter boilerplate with clean architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # UI & Icons
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
    # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2  # Storage & Database
  shared_preferences: ^2.2.2
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.1
  
  # Google Drive Sync & Authentication
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
    # Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: 0.20.2
  
  # Platform Integration
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  
  # Advanced Theming
  dynamic_color: ^1.7.0
  auto_size_text: ^3.0.0
  flutter_colorpicker: ^1.0.3
  easy_localization: ^3.0.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
    # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1
  injectable_generator: ^2.4.1
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
assets:
  - assets/icons/
  - assets/images/
  - assets/translations/
  - assets/data/
  
fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd-Black.otf
          weight: 700
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700