    name: Check Markdown Links

    # Run this workflow on pushes to the main branches and on any pull request.
    on:
      push:
        branches:
          - main
          - docs-revamp
      pull_request:
        branches:
          - main
          - docs-revamp

    jobs:
      markdown-link-check:
        runs-on: ubuntu-latest
        steps:
          # Step 1: Check out the repository's code so the action can access it.
          - name: Checkout Code
            uses: actions/checkout@v4

          # Step 2: Run the markdown-link-check action.
          # This uses a pre-built action that wraps the tool for convenience.
          - name: Check Links
            uses: gaurav-nelson/github-action-markdown-link-check@v1
            with:
              # We specify the 'docs' folder to check all markdown files within it.
              use-quiet-mode: 'yes'
              folder-path: 'finance/docs/'
              # This config tells the checker how to handle certain links.
              # For example, it will ignore the dummy 'YOUR_GOOGLE_CLIENT_ID' link.
              config-file: '.github/workflows/mlc_config.json'